import { Injectable } from '@nestjs/common';
import type { LoadedCertificate } from './certificate';
import { buildDpsXml, escapeXml, formatDateTimeBr, NFSE_NAMESPACE } from './dps-builder';
import { NfseRejectedError } from './errors';
import type { DpsData, EmitResult, NfseGateway } from './nfse-gateway';
import { signXml } from './xml-signer';

const FAKE_PDF = Buffer.from('%PDF-1.4\n%fake DANFSe generated by FakeNfseGateway\n%%EOF\n');

@Injectable()
export class FakeNfseGateway implements NfseGateway {
  readonly emitted = new Map<string, EmitResult>();
  private pendingRejection: NfseRejectedError | null = null;

  rejectNext(code: string, message: string) {
    this.pendingRejection = new NfseRejectedError(code, message);
  }

  async emit(dps: DpsData, certificate: LoadedCertificate): Promise<EmitResult> {
    this.consumeRejection();
    const { xml } = buildDpsXml(dps);
    const xmlDps = signXml(xml, certificate, 'infDPS');
    const chaveAcesso = this.fakeChave(dps);
    const numeroNfse = String(dps.numero);
    const xmlNfse =
      `<NFSe xmlns="${NFSE_NAMESPACE}" versao="1.00"><infNFSe Id="NFS${chaveAcesso}">` +
      `<nNFSe>${numeroNfse}</nNFSe><dhProc>${formatDateTimeBr(new Date())}</dhProc>` +
      `<emit><CNPJ>${dps.prestador.cnpj}</CNPJ></emit>` +
      `<toma><xNome>${escapeXml(dps.tomador.nome)}</xNome></toma>` +
      `</infNFSe>${xmlDps}</NFSe>`;
    const result = { chaveAcesso, numeroNfse, xmlDps, xmlNfse };
    this.emitted.set(chaveAcesso, result);
    return result;
  }

  async cancel(
    chaveAcesso: string,
    _motivo: string,
    _dps: Pick<DpsData, 'ambiente' | 'prestador'>,
    _certificate: LoadedCertificate,
  ): Promise<void> {
    this.consumeRejection();
    if (!this.emitted.has(chaveAcesso)) {
      throw new NfseRejectedError('E9999', 'NFS-e não encontrada');
    }
  }

  async pdf(chaveAcesso: string, _certificate: LoadedCertificate): Promise<Buffer> {
    if (!this.emitted.has(chaveAcesso)) {
      throw new NfseRejectedError('E9999', 'NFS-e não encontrada');
    }
    return FAKE_PDF;
  }

  private consumeRejection() {
    if (this.pendingRejection) {
      const error = this.pendingRejection;
      this.pendingRejection = null;
      throw error;
    }
  }

  /** cMun(7) + tpAmb(1) + AAMM(4) + CNPJ(14) + serie... — 50 digits, deterministic per DPS. */
  private fakeChave(dps: DpsData): string {
    const now = new Date();
    const aamm = `${String(now.getFullYear()).slice(2)}${String(now.getMonth() + 1).padStart(2, '0')}`;
    const head = dps.prestador.codigoMunicipio + (dps.ambiente === 'producao' ? '1' : '2') + aamm + dps.prestador.cnpj;
    const tail = String(dps.numero).padStart(15, '0') + String(Date.now()).slice(-9);
    return (head + tail).padEnd(50, '0').slice(0, 50);
  }
}
